/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aps.banco.ui;

import Exceptions.ContaException;
import Exceptions.MovimentacaoException;
import br.com.aps.banco.ContaBancaria;
import javax.swing.JOptionPane;

/**
 *
 * @author ti
 */
public class MovimentarConta extends javax.swing.JInternalFrame {
        ContaBancaria conta;
        int radio = 0;
    /**
     * Creates new form MovimentarConta
     */
    public MovimentarConta() {
        initComponents();
        RadioGroupOperacoes.add(radioDepositar);
        RadioGroupOperacoes.add(radioSacar);
        RadioGroupOperacoes.add(radioTransferir);
        btnConfirmar.setEnabled(false);
        lblNumeroContaDestino.setEnabled(false);
        tfNumeroContaDestino.setEnabled(false);
        
    }
    
    public void limparFormulario() {
        tfNumeroContaDestino.setText("");
        tfValor.setText("");
        tfNumeroConta.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioGroupOperacoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNumeroConta = new javax.swing.JFormattedTextField();
        btnLocalizar = new javax.swing.JButton();
        radioDepositar = new javax.swing.JRadioButton();
        radioSacar = new javax.swing.JRadioButton();
        radioTransferir = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tfValor = new javax.swing.JFormattedTextField();
        lblNumeroContaDestino = new javax.swing.JLabel();
        tfNumeroContaDestino = new javax.swing.JFormattedTextField();
        btnConfirmar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações com Contas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Informa o número da conta:");

        tfNumeroConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        radioDepositar.setText("Depositar");
        radioDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDepositarActionPerformed(evt);
            }
        });

        radioSacar.setText("Sacar");
        radioSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSacarActionPerformed(evt);
            }
        });

        radioTransferir.setText("Transferir");
        radioTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTransferirActionPerformed(evt);
            }
        });

        jLabel2.setText("Informe o valor: ");

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lblNumeroContaDestino.setText("Número da Conta:");

        tfNumeroContaDestino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNumeroConta))
                        .addGap(58, 58, 58)
                        .addComponent(btnLocalizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroContaDestino)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radioDepositar)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfValor, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(tfNumeroContaDestino)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(radioSacar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(radioTransferir)))))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLocalizar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDepositar)
                    .addComponent(radioSacar)
                    .addComponent(radioTransferir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroContaDestino)
                    .addComponent(tfNumeroContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void radioDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDepositarActionPerformed
       lblNumeroContaDestino.setEnabled(false);
       tfNumeroContaDestino.setEnabled(false);
       radio = 1;
    }//GEN-LAST:event_radioDepositarActionPerformed

    private void radioSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSacarActionPerformed
       lblNumeroContaDestino.setEnabled(false);
       tfNumeroContaDestino.setEnabled(false);
       radio = 2;
    }//GEN-LAST:event_radioSacarActionPerformed

    private void radioTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTransferirActionPerformed
       lblNumeroContaDestino.setEnabled(true);
       tfNumeroContaDestino.setEnabled(true);
       radio = 3;
    }//GEN-LAST:event_radioTransferirActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        try {
            conta = BancoUI.banco.procurarConta(Long.parseLong(tfNumeroConta.getText()));
            if (conta != null) {
                btnConfirmar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Conta Não Encontrada!");
                tfNumeroConta.requestFocusInWindow();
            }
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!");;
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            if (radio == 1) {
                conta.depositar(Double.parseDouble(tfValor.getText()));
                JOptionPane.showMessageDialog(rootPane, "Depositado com sucesso!");
                limparFormulario();
            } else if (radio == 2) {
                conta.sacar(Double.parseDouble(tfValor.getText()));
                JOptionPane.showMessageDialog(rootPane, "Sacado com sucesso!");
                limparFormulario();
            } else {
                ContaBancaria contaPara = BancoUI.banco.procurarConta(Long.parseLong(tfNumeroContaDestino.getText()));
                if (contaPara!=null) {
                    if (conta.getNumeroConta() == contaPara.getNumeroConta()) {
                        throw new MovimentacaoException("Conta de origem igual a de destino!");
                    }
                    conta.transferir(Double.parseDouble(tfValor.getText()), conta, contaPara);
                    JOptionPane.showMessageDialog(rootPane, "Transferência realizada com sucessso!");
                    limparFormulario();
                } else {
                    throw new ContaException("Conta de destino não encontrada!");
                }
            }
        } catch (MovimentacaoException me) {
            JOptionPane.showMessageDialog(rootPane, me.getMessage());
        } catch (ContaException ce) {
            JOptionPane.showMessageDialog(rootPane, ce.getMessage());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!");;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }   
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioGroupOperacoes;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumeroContaDestino;
    private javax.swing.JRadioButton radioDepositar;
    private javax.swing.JRadioButton radioSacar;
    private javax.swing.JRadioButton radioTransferir;
    private javax.swing.JFormattedTextField tfNumeroConta;
    private javax.swing.JFormattedTextField tfNumeroContaDestino;
    private javax.swing.JFormattedTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
